# Generated by Django 5.2.7 on 2025-10-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesystemobject',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
