# Generated by Django 5.2.7 on 2025-10-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='page_table',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='process',
            name='status',
            field=models.CharField(choices=[('Ready', 'Ready'), ('Running', 'Running'), ('Blocked', 'Blocked'), ('Finished', 'Finished')], default='Ready', max_length=10),
        ),
    ]
